export const cardCardTexts = [
  "The cat is cuddly",
  "The cat meows",
  "The cat purrs when they are happy",
  "The cat loves to play with yarn",
  "The catnip drives some cats crazy",
  "The cat has retractable claws",
  "The cat can sleep up to 16 hours a day",
  "The cat grooms itself regularly",
  "The cat has excellent night vision",
  "The cat communicates through meowing",
  "The cat has a strong sense of smell",
  "The cat is a crepuscular animal",
  "The cat marks its territory with scent glands",
  "The cat has five toes on its front paws and four on its back paws",
  "The cat's whiskers are highly sensitive",
  "The cat can jump up to six times its body length",
  "The cat is an obligate carnivore",
  "The cat is known for its agility",
  "The cat has a unique grooming behavior called 'kneading'",
  "The cat uses its tail for balance",
  "The cat has a specific hunting behavior called 'stalking'",
  "The cat has individual preferences for food and toys",
  "The cat has a territory that it defends against other cats",
  "The cat has a variety of vocalizations to express itself",
];
