import { randomArrayItem } from "../util/randomArrayItem";
import { cardCardTexts } from "./catCardTexts";
import { MassAppealCard } from "./massAppealDeck";

export const catDeck: MassAppealCard[] = [
  {
    headName: "1",
    value: 1,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Orange Cat",
    emoji: "🐈",
    color: "orange",
  },
  {
    headName: "2",
    value: 2,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Orange Cat",
    emoji: "🐈",
    color: "orange",
  },
  {
    headName: "3",
    value: 3,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Orange Cat",
    emoji: "🐈",
    color: "orange",
  },
  {
    headName: "4",
    value: 4,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Orange Cat",
    emoji: "🐈",
    color: "orange",
  },
  {
    headName: "5",
    value: 5,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Orange Cat",
    emoji: "🐈",
    color: "orange",
  },
  {
    headName: "6",
    value: 6,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Orange Cat",
    emoji: "🐈",
    color: "orange",
  },
  ///
  {
    headName: "1",
    value: 1,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Grey Cat",
    emoji: "😼",
    color: "grey",
  },
  {
    headName: "2",
    value: 2,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Grey Cat",
    emoji: "😼",
    color: "grey",
  },
  {
    headName: "3",
    value: 3,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Grey Cat",
    emoji: "😼",
    color: "grey",
  },
  {
    headName: "4",
    value: 4,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Grey Cat",
    emoji: "😼",
    color: "grey",
  },
  {
    headName: "5",
    value: 5,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Grey Cat",
    emoji: "😼",
    color: "grey",
  },
  {
    headName: "6",
    value: 6,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Grey Cat",
    emoji: "😼",
    color: "grey",
  },
  ///
  {
    headName: "1",
    value: 1,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Black Cat",
    emoji: "🐈‍⬛",
    color: "Black",
  },
  {
    headName: "2",
    value: 2,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Black Cat",
    emoji: "🐈‍⬛",
    color: "Black",
  },
  {
    headName: "3",
    value: 3,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Black Cat",
    emoji: "🐈‍⬛",
    color: "Black",
  },
  {
    headName: "4",
    value: 4,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Black Cat",
    emoji: "🐈‍⬛",
    color: "Black",
  },
  {
    headName: "5",
    value: 5,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Black Cat",
    emoji: "🐈‍⬛",
    color: "Black",
  },
  {
    headName: "6",
    value: 6,
    infoSection: randomArrayItem(cardCardTexts),
    type: "Black Cat",
    emoji: "🐈‍⬛",
    color: "Black",
  },
  ///
  {
    headName: "1",
    value: 1,
    infoSection: randomArrayItem(cardCardTexts),
    type: "White Cat",
    emoji: "🐱",
    color: "White",
  },
  {
    value: 2,
    headName: "2",
    infoSection: randomArrayItem(cardCardTexts),
    type: "White Cat",
    emoji: "🐱",
    color: "White",
  },
  {
    headName: "3",
    value: 3,
    infoSection: randomArrayItem(cardCardTexts),
    type: "White Cat",
    emoji: "🐱",
    color: "White",
  },
  {
    headName: "4",
    value: 3,
    infoSection: randomArrayItem(cardCardTexts),
    type: "White Cat",
    emoji: "🐱",
    color: "White",
  },
  {
    headName: "4",
    value: 4,
    infoSection: randomArrayItem(cardCardTexts),
    type: "White Cat",
    emoji: "🐱",
    color: "White",
  },
  {
    headName: "5",
    value: 5,
    infoSection: randomArrayItem(cardCardTexts),
    type: "White Cat",
    emoji: "🐱",
    color: "White",
  },
  // multi

  {
    headName: "Mating",
    infoSection: "Meow",
    type: "Multiplier",
    emoji: "💗",
    color: "gold",
  },
  {
    headName: "Mating",
    infoSection: "Meow",
    type: "Multiplier",
    emoji: "💗",
    color: "gold",
  },
  {
    headName: "Mating",
    infoSection: "Meow",
    type: "Multiplier",
    emoji: "💗",
    color: "gold",
  },
];

export const catDeckOutcomes: MassAppealCard[] = [
  // outcomes
  {
    headName: "Mixed Colors",
    multiplier: 8,
    type: "Outcome",
    emoji: "🎨",
    color: "bisque",
  },
  {
    headName: "Matching Colors",
    multiplier: 12,
    type: "Outcome",
    emoji: "🟫",
    color: "bisque",
  },
  {
    headName: "Mating",
    multiplier: 4,
    type: "Outcome",
    emoji: "😻",
    color: "bisque",
  },
  {
    headName: "Cat Pack",
    multiplier: 2,
    type: "Outcome",
    emoji: "🙀",
    color: "bisque",
  },
  {
    headName: "No Cats",
    multiplier: 0,
    type: "Outcome",
    emoji: "🏞️",
    color: "bisque",
  },
];
// 🐅🐯
