export const importExportSaveLocalization = {
	_cancel: {
		_en: `Cancel`,
		_de: `Abbrechen`,
		_fr: `Annuler`,
		_es: `Cancelar`,
		_zh: `取消`,
		_ja: `キャンセル`,
		_ko: `취소`,
		_ru: `Отмена`,
		_it: `Annulla`,
		_pt: `Cancelar`,
		_hi: `रद्द करें`,
	},
	loadAGame: {
		_en: "How to Load a Game",
		_de: "Um ein Spiel zu laden",
		_es: "Para cargar un juego",
		_fr: "Pour charger un jeu",
		_zh: "加载游戏",
		_ja: "ゲームを読み込むには",
		_ko: "게임을 로드하려면",
		_ru: "Чтобы загрузить игру",
		_it: "Per caricare un gioco",
		_pt: "Para carregar um jogo",
		_hi: "एक खेल लोड करने के लिए",
	},
	saveLoading: {
		_en: "Save Loading.",
		_de: "Speichern wird geladen.",
		_es: "Cargando guardado.",
		_fr: "Chargement de la sauvegarde.",
		_zh: "保存加载中。",
		_ja: "セーブロード中。",
		_ko: "저장 로드 중입니다.",
		_ru: "Загрузка сохранения.",
		_it: "Caricamento del salvataggio.",
		_pt: "Carregando salvamento.",
		_hi: "सहेजना लोड हो रहा है।",
	},
	invalidSave: {
		_en: "Invalid or corrupt save file.",
		_de: "Ungültige oder beschädigte Speicherdatei.",
		_es: "Archivo de guardado inválido o corrupto.",
		_fr: "Fichier de sauvegarde invalide ou corrompu.",
		_zh: "无效或损坏的保存文件。",
		_ja: "無効または破損したセーブファイル。",
		_ko: "유효하지 않거나 손상된 저장 파일입니다.",
		_ru: "Недействительный или повреждённый файл сохранения.",
		_it: "File di salvataggio non valido o danneggiato.",
		_pt: "Arquivo de salvamento inválido ou corrompido.",
		_hi: "अमान्य या भ्रष्ट सहेजने वाली फ़ाइल।",
	},
	SaveSuccessful: {
		_en: "Save Successful",
		_de: "Speichern Erfolgreich",
		_es: "Guardado Exitoso",
		_fr: "Sauvegarde Réussie",
		_zh: "保存成功",
		_ja: "保存成功",
		_ko: "저장 성공",
		_ru: "Сохранение успешно",
		_it: "Salvataggio riuscito",
		_pt: "Salvamento bem-sucedido",
		_hi: "सहेजना सफल",
	},
	SaveCopied: {
		_en: "Save was copied to your clipboard",
		_de: "Speicherung wurde in die Zwischenablage kopiert",
		_es: "El guardado fue copiado a tu portapapeles",
		_fr: "La sauvegarde a été copiée dans votre presse-papiers",
		_zh: "保存已复制到剪贴板",
		_ja: "保存がクリップボードにコピーされました",
		_ko: "저장이 클립보드에 복사되었습니다",
		_ru: "Сохранение было скопировано в буфер обмена",
		_it: "Il salvataggio è stato copiato negli appunti",
		_pt: "O salvamento foi copiado para a área de transferência",
		_hi: "सहेजना आपकी क्लिपबोर्ड पर कॉपी किया गया",
	},
	copySave: {
		_en: "Copy Save String",
		_de: "Speicherzeichenfolge kopieren",
		_es: "Copiar cadena de guardado",
		_fr: "Copier la chaîne de sauvegarde",
		_zh: "复制保存字符串",
		_ja: "保存文字列をコピー",
		_ko: "저장 문자열 복사",
		_ru: "Копировать строку сохранения",
		_it: "Copia la stringa di salvataggio",
		_pt: "Copiar String de Salvamento",
		_hi: "सहेजने की स्ट्रिंग कॉपी करें",
	},
	loadSave: {
		_en: "Load Save String",
		_de: "Speicherzeichenfolge laden",
		_es: "Cargar cadena de guardado",
		_fr: "Charger la chaîne de sauvegarde",
		_zh: "加载保存字符串",
		_ja: "保存文字列を読み込む",
		_ko: "저장 문자열 로드",
		_ru: "Загрузить строку сохранения",
		_it: "Carica la stringa di salvataggio",
		_pt: "Carregar String de Salvamento",
		_hi: "सहेजने की स्ट्रिंग लोड करें",
	},
	loadstep1: {
		_en: "1. Paste save string in the text box",
		_de: "1. Fügen Sie die Speicherzeichenfolge in das Textfeld ein",
		_es: "1. Pega la cadena de guardado en el cuadro de texto",
		_fr: "1. Collez la chaîne de sauvegarde dans la zone de texte",
		_zh: "1. 将保存字符串粘贴到文本框中",
		_ja: "1. 保存文字列をテキストボックスに貼り付ける",
		_ko: "1. 텍스트 상자에 저장 문자열을 붙여넣기",
		_ru: "1. Вставьте строку сохранения в текстовое поле",
		_it: "1. Incolla la stringa di salvataggio nella casella di testo",
		_pt: "1. Cole a stringa de salvamento na caixa de texto",
		_hi: "1. सहेजने की स्ट्रिंग को टेक्स्ट बॉक्स में पेस्ट करें",
	},
	loadstep2: {
		_en: "2. Click load save string",
		_de: '2. Klicken Sie auf "Speicherzeichenfolge laden"',
		_es: "2. Haz clic en cargar cadena de guardado",
		_fr: '2. Cliquez sur "Charger la chaîne de sauvegarde"',
		_zh: "2. 点击“加载保存字符串”",
		_ja: "2. 「保存文字列を読み込む」をクリックする",
		_ko: '2. "저장 문자열 로드"를 클릭하세요',
		_ru: "2. Нажмите «Загрузить строку сохранения»",
		_it: '2. Clicca su "Carica la stringa di salvataggio"',
		_pt: "2. Clique em carregar string de salvamento",
		_hi: '2. "सहेजने की स्ट्रिंग लोड करें" पर क्लिक करें',
	},
	saveBoxPlaceholder: {
		_en: "Enter a SAVE STRING...",
		_de: "Geben Sie eine SPEICHERZEICHENFOLGE ein...",
		_es: "Introduce una CADENA DE GUARDADO...",
		_fr: "Entrez une CHAÎNE DE SAUVEGARDE...",
		_zh: "输入保存字符串...",
		_ja: "セーブ文字列を入力...",
		_ko: "저장 문자열을 입력...",
		_ru: "Введите строку сохранения...",
		_it: "Inserisci una STRINGA DI SALVATAGGIO...",
		_pt: "Digite uma STRING DE SALVAMENTO...",
		_hi: "एक सहेजने की स्ट्रिंग दर्ज करें...",
	},
	saveBoxPlaceholderBoxer: {
		_en: `Enter a BOXER STRING...`,
		_de: `Gib einen BOXER-STRING ein...`,
		_fr: `Entrez une CHAÎNE DE BOXEUR...`,
		_es: `Introduce una CADENA DE BOXEADOR...`,
		_zh: `请输入拳手字符串...`,
		_ja: `ボクサー文字列を入力してください...`,
		_ko: `복서 문자열을 입력하세요...`,
		_ru: `Введите СТРОКУ БОКСЁРА...`,
		_it: `Inserisci una STRINGA DEL PUGILE...`,
		_pt: `Digite uma STRING DO BOXEADOR...`,
		_hi: `एक बॉक्सर स्ट्रिंग दर्ज करें...`,
	},
	saveFile: {
		_en: "Save File",
		_de: "Spielstand speichern",
		_es: "Guardar archivo del juego",
		_fr: "Enregistrer le fichier de jeu",
		_zh: "保存游戏文件",
		_ja: "ゲームファイルを保存",
		_ko: "게임 파일 저장",
		_ru: "Сохранить файл игры",
		_it: "Salva il file di gioco",
		_pt: "Salvar arquivo do jogo",
		_hi: "खेल फ़ाइल सहेजें",
	},
	loadFile: {
		_en: "Load File",
		_de: "Spielstand laden",
		_es: "Cargar archivo del juego",
		_fr: "Charger le fichier de jeu",
		_zh: "加载游戏文件",
		_ja: "ゲームファイルを読み込む",
		_ko: "게임 파일 로드",
		_ru: "Загрузить файл игры",
		_it: "Carica il file di gioco",
		_pt: "Carregar arquivo do jogo",
		_hi: "खेल फ़ाइल लोड करें",
	},
	newGame: {
		_en: `New Game`,
		_de: `Neues Spiel`,
		_fr: `Nouvelle Partie`,
		_es: `Nuevo Juego`,
		_zh: `新游戏`,
		_ja: `新しいゲーム`,
		_ko: `새 게임`,
		_ru: `Новая Игра`,
		_it: `Nuova Partita`,
		_pt: `Novo Jogo`,
		_hi: `नया खेल`,
	},
	clearDataNewGame: {
		_en: `Clear data and start new game`,
		_de: `Daten löschen und neues Spiel starten`,
		_fr: `Effacer les données et commencer une nouvelle partie`,
		_es: `Borrar datos y empezar un nuevo juego`,
		_zh: `清除数据并开始新游戏`,
		_ja: `データを消去して新しいゲームを始める`,
		_ko: `데이터를 삭제하고 새 게임 시작`,
		_ru: `Очистить данные и начать новую игру`,
		_it: `Cancella i dati e inizia una nuova partita`,
		_pt: `Limpar dados e começar um novo jogo`,
		_hi: `डेटा साफ़ करें और नया खेल शुरू करें`,
	},
	warningClearSave: {
		_en: `Warning - this will clear your save file`,
		_de: `Warnung - Dies wird Ihre gespeicherte Datei löschen`,
		_fr: `Attention - Cela effacera votre fichier de sauvegarde`,
		_es: `Advertencia - Esto borrará tu archivo guardado`,
		_zh: `警告 - 这将清除您的存档文件`,
		_ja: `警告 - セーブデータが削除されます`,
		_ko: `경고 - 저장 파일이 삭제됩니다`,
		_ru: `Предупреждение - это удалит ваш сохранённый файл`,
		_it: `Avviso - Questo cancellerà il tuo file di salvataggio`,
		_pt: `Aviso - Isso apagará seu arquivo salvo`,
		_hi: `चेतावनी - यह आपकी सहेजी गई फ़ाइल को साफ़ कर देगा`,
	},
};
